### ISSUE TITLE
Strapi Einführung

### ISSUE THREAD

**Issue by VitaliaSvirskaja** [TSC-Rot-Gold-Casino-Nurnberg-e-V/rgc-cms#9]
# Ziel
Einer kleinen Testgruppe soll das neue CMS vorgestellt werden. Diese Testgruppe soll nach der Einführung das CMS selbstständig testen und Feedback hinterlassen (positives, negatives, fehlende Funktionen).

# Teilnehmer
- Peat
- Jelena
- Mila

# Voraussetzungen
- [x] grundlegender [Contentfluss](https://github.com/TSC-Rot-Gold-Casino-Nurnberg-e-V/diagrams/blob/main/content-flow.md) muss funktionieren 
- [x] Anleitung für die Nutzung des CMS muss vorbereitet sein 
- [x] grobe Struktur für den Termin muss vorbereitet sein
- [x] [Newsübersichtsseite](https://github.com/orgs/TSC-Rot-Gold-Casino-Nurnberg-e-V/projects/1/views/1?pane=issue&itemId=18614061) und einzelne [Newsseiten](https://github.com/orgs/TSC-Rot-Gold-Casino-Nurnberg-e-V/projects/1/views/1?pane=issue&itemId=18614201) müssen als grundlegendes Proof of Concept bestehen
- [x] grundlegende Newsfelder müssen mit dem bestehenden PortUna mindestens übereinstimmen

# Termin Agenda
// ToDo

# Anleitung
https://docs.strapi.io/user-docs/latest/content-manager/writing-content.html#filling-up-fields

# TODOs
- [x] Präsentation an Interessenten schicken
